### ISSUE TITLE
C API AUD_readSound() the param 

### ISSUE THREAD

**Issue by DJLinux** [audaspace/audaspace#14]
I wrote a FreeBASIC binding for the audaspace C-API the last param "interrupt" short*  is not documented in the include or sourcode file how to use it ?

by the way i'm blind or isn't there a C-API documentation ?

Thank you

Joshy

**Comment by neXyon** [comment]
There kind of is - see the main paragraph here: https://audaspace.github.io/bindings/index.html

`AUD_readSound()` is part of `AUD_Special.h` a header that is basically containing specialized functions to be used by Blender. Thus the API can change any time and it's not considered part of the official API. That's why there is also no Python binding for it and no documentation.

But if you're still curious about `interrupt`: It must point to a short that equals 0. If it is set to a non-zero value, the method will be interrupted and return 0. This can be used in multi-threaded applications to interrupt reading if it takes too long.
